name: seda
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+13

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  loading_animation_widget: ^1.2.0+3
  google_maps_flutter: ^2.4.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.2
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.1.1
  fl_country_code_picker: ^0.1.5
  flutter_rating_bar: ^4.0.1
  qr_code_scanner: ^1.0.1
  circular_countdown_timer: ^0.2.3
  contacts_service: ^0.6.3
  drawing_animation: ^1.0.0
  animations: ^2.0.7
  image_picker: ^1.0.1
  socket_io_client: ^2.0.0-beta.2
  flutter_local_notifications: ^15.1.0+1
  firebase_crashlytics: any
  flutter_polyline_points: ^1.0.0
  snapping_sheet: ^3.1.0
  audioplayers: ^2.0.0
  permission_handler: ^10.2.0
  intl_phone_number_input: ^0.7.0+2
  flutter_google_places: ^0.3.0
  webview_flutter: ^3.0.4
  pull_to_refresh: ^2.0.0
  path_provider: ^2.0.14
  audio_waveforms: ^1.0.3
  flutter_switch: ^0.3.2
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.11
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  firebase_auth: ^4.4.0
  maps_toolkit: ^2.0.1
  pin_code_fields: ^8.0.1

dependency_overrides:
  xml: ^6.1.0
  google_api_headers: ^1.4.0
  http: ^0.13.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  dart_code_metrics: ^5.7.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/appIcon.png"
  image_path_ios: "assets/images/appIconIos.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/map/

  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter.ttf
     - family: Calibri
       fonts:
         - asset: assets/fonts/CalibriRegular.ttf
